import type { FullAnalysisResult } from "../analyzers/types.js";
import { getScoreLabel } from "../diagnostics/scorer.js";
import type { DiagnosticResult } from "../diagnostics/types.js";

export function generateHtmlReport(
	analysis: FullAnalysisResult | null,
	diagnostic: DiagnosticResult | null,
): string {
	const scoreColor =
		(diagnostic?.score ?? 0) >= 75
			? "#22c55e"
			: (diagnostic?.score ?? 0) >= 50
				? "#eab308"
				: "#ef4444";

	return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>AgentTuner Report</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #0f172a; color: #e2e8f0; padding: 2rem; max-width: 900px; margin: 0 auto; }
  h1 { font-size: 1.8rem; margin-bottom: 0.5rem; color: #38bdf8; }
  h2 { font-size: 1.3rem; margin: 2rem 0 1rem; color: #94a3b8; border-bottom: 1px solid #334155; padding-bottom: 0.5rem; }
  .subtitle { color: #64748b; margin-bottom: 2rem; }
  .score-card { background: #1e293b; border-radius: 12px; padding: 2rem; text-align: center; margin-bottom: 2rem; }
  .score-value { font-size: 3rem; font-weight: bold; color: ${scoreColor}; }
  .score-label { color: #94a3b8; font-size: 1.1rem; }
  .stats-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 1rem; margin-bottom: 2rem; }
  .stat-card { background: #1e293b; border-radius: 8px; padding: 1.2rem; }
  .stat-label { color: #64748b; font-size: 0.85rem; text-transform: uppercase; }
  .stat-value { font-size: 1.5rem; font-weight: bold; margin-top: 0.3rem; }
  .issue { background: #1e293b; border-radius: 8px; padding: 1rem; margin-bottom: 0.5rem; border-left: 3px solid; }
  .issue.error { border-color: #ef4444; }
  .issue.warning { border-color: #eab308; }
  .issue.info { border-color: #3b82f6; }
  .issue-title { font-weight: 600; margin-bottom: 0.3rem; }
  .issue-suggestion { color: #94a3b8; font-size: 0.9rem; }
  .badge { display: inline-block; padding: 0.2rem 0.6rem; border-radius: 4px; font-size: 0.75rem; font-weight: 600; text-transform: uppercase; }
  .badge.error { background: #7f1d1d; color: #fca5a5; }
  .badge.warning { background: #713f12; color: #fde68a; }
  .badge.info { background: #1e3a5f; color: #93c5fd; }
  .waste-bar { display: flex; align-items: center; gap: 0.5rem; margin-bottom: 0.5rem; }
  .waste-bar-fill { height: 20px; background: #ef4444; border-radius: 4px; min-width: 4px; }
  .waste-bar-label { color: #94a3b8; font-size: 0.85rem; white-space: nowrap; }
  .footer { margin-top: 3rem; text-align: center; color: #475569; font-size: 0.85rem; }
</style>
</head>
<body>
<h1>AgentTuner Report</h1>
<p class="subtitle">Generated ${new Date().toLocaleDateString()}</p>

${diagnostic ? renderDiagnostic(diagnostic) : ""}
${analysis ? renderAnalysis(analysis) : ""}

<div class="footer">
  <p>Generated by <strong>AgentTuner</strong> — Auto-optimize your AI coding agent configs</p>
</div>
</body>
</html>`;
}

function renderDiagnostic(d: DiagnosticResult): string {
	const scoreColor = d.score >= 75 ? "#22c55e" : d.score >= 50 ? "#eab308" : "#ef4444";

	return `
<h2>Config Diagnostic</h2>
<div class="score-card">
  <div class="score-value" style="color: ${scoreColor}">${d.score}/100</div>
  <div class="score-label">${getScoreLabel(d.score)}</div>
</div>
<div class="stats-grid">
  <div class="stat-card">
    <div class="stat-label">File</div>
    <div class="stat-value">${d.filePath}</div>
  </div>
  <div class="stat-card">
    <div class="stat-label">Lines</div>
    <div class="stat-value">${d.lineCount}</div>
  </div>
  <div class="stat-card">
    <div class="stat-label">Issues</div>
    <div class="stat-value">${d.issues.length}</div>
  </div>
  <div class="stat-card">
    <div class="stat-label">Sections</div>
    <div class="stat-value">${d.sections.length}</div>
  </div>
</div>

${
	d.issues.length > 0
		? `<h2>Issues</h2>${d.issues
				.map(
					(i) => `
<div class="issue ${i.severity}">
  <div class="issue-title"><span class="badge ${i.severity}">${i.severity}</span> ${i.message}</div>
  <div class="issue-suggestion">→ ${i.suggestion}</div>
</div>`,
				)
				.join("")}`
		: ""
}

${d.missingSections.length > 0 ? `<h2>Missing Sections</h2><ul>${d.missingSections.map((s) => `<li>${s}</li>`).join("")}</ul>` : ""}`;
}

function renderAnalysis(a: FullAnalysisResult): string {
	const maxTokens = Math.max(...a.topWasteCategories.map((c) => c.tokens), 1);

	return `
<h2>Session Analysis</h2>
<div class="stats-grid">
  <div class="stat-card">
    <div class="stat-label">Sessions</div>
    <div class="stat-value">${a.totalSessions}</div>
  </div>
  <div class="stat-card">
    <div class="stat-label">Total Tokens</div>
    <div class="stat-value">${formatNumber(a.totalTokensUsed)}</div>
  </div>
  <div class="stat-card">
    <div class="stat-label">Wasted Tokens</div>
    <div class="stat-value" style="color: #ef4444">${formatNumber(a.estimatedWastedTokens)}</div>
  </div>
  <div class="stat-card">
    <div class="stat-label">Wasted Cost</div>
    <div class="stat-value" style="color: #ef4444">$${a.estimatedWastedCost.toFixed(2)}</div>
  </div>
</div>

${
	a.topWasteCategories.length > 0
		? `<h2>Waste Categories</h2>${a.topWasteCategories
				.map(
					(c) => `
<div class="waste-bar">
  <div class="waste-bar-fill" style="width: ${(c.tokens / maxTokens) * 200}px"></div>
  <div class="waste-bar-label">${formatWasteType(c.type)} — ${formatNumber(c.tokens)} tokens (${c.count}x)</div>
</div>`,
				)
				.join("")}`
		: ""
}`;
}

function formatNumber(n: number): string {
	if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(1)}M`;
	if (n >= 1_000) return `${(n / 1_000).toFixed(1)}K`;
	return String(n);
}

function formatWasteType(type: string): string {
	const labels: Record<string, string> = {
		"repeated-read": "Repeated File Reads",
		"repeated-command": "Repeated Commands",
		"exploration-loop": "Exploration Loops",
		"file-churn": "File Churn",
		"idle-turn": "Idle Turns",
		"empty-tool-result": "Empty Tool Results",
		"large-output-ignored": "Ignored Large Outputs",
	};
	return labels[type] ?? type;
}
