import type { FullAnalysisResult } from "../analyzers/types.js";
import { getScoreLabel } from "../diagnostics/scorer.js";
import type { DiagnosticResult } from "../diagnostics/types.js";

export function generateMarkdownReport(
	analysis: FullAnalysisResult | null,
	diagnostic: DiagnosticResult | null,
): string {
	const lines: string[] = [];

	lines.push("# AgentTuner Report");
	lines.push("");
	lines.push(`> Generated ${new Date().toLocaleDateString()}`);
	lines.push("");

	if (diagnostic) {
		lines.push("## Config Diagnostic");
		lines.push("");
		lines.push(`**Score:** ${diagnostic.score}/100 (${getScoreLabel(diagnostic.score)})`);
		lines.push(`**File:** ${diagnostic.filePath} (${diagnostic.lineCount} lines)`);
		lines.push("");

		if (diagnostic.issues.length > 0) {
			lines.push("### Issues");
			lines.push("");
			for (const issue of diagnostic.issues) {
				const icon = issue.severity === "error" ? "🔴" : issue.severity === "warning" ? "🟡" : "🔵";
				lines.push(`- ${icon} **${issue.message}**`);
				lines.push(`  - → ${issue.suggestion}`);
			}
			lines.push("");
		}

		if (diagnostic.missingSections.length > 0) {
			lines.push("### Missing Sections");
			lines.push("");
			for (const section of diagnostic.missingSections) {
				lines.push(`- ${section}`);
			}
			lines.push("");
		}
	}

	if (analysis) {
		lines.push("## Session Analysis");
		lines.push("");
		lines.push(`| Metric | Value |`);
		lines.push(`|--------|-------|`);
		lines.push(`| Sessions | ${analysis.totalSessions} |`);
		lines.push(`| Total Tokens | ${formatNumber(analysis.totalTokensUsed)} |`);
		lines.push(`| Wasted Tokens | ${formatNumber(analysis.estimatedWastedTokens)} |`);
		lines.push(`| Wasted Cost | $${analysis.estimatedWastedCost.toFixed(2)} |`);
		lines.push("");

		if (analysis.topWasteCategories.length > 0) {
			lines.push("### Top Waste Categories");
			lines.push("");
			for (const cat of analysis.topWasteCategories) {
				lines.push(
					`- **${formatWasteType(cat.type)}**: ${formatNumber(cat.tokens)} tokens (${cat.count} occurrences)`,
				);
			}
			lines.push("");
		}
	}

	lines.push("---");
	lines.push("*Generated by [AgentTuner](https://github.com/yourname/agenttuner)*");

	return lines.join("\n");
}

function formatNumber(n: number): string {
	if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(1)}M`;
	if (n >= 1_000) return `${(n / 1_000).toFixed(1)}K`;
	return String(n);
}

function formatWasteType(type: string): string {
	const labels: Record<string, string> = {
		"repeated-read": "Repeated File Reads",
		"repeated-command": "Repeated Commands",
		"exploration-loop": "Exploration Loops",
		"file-churn": "File Churn",
		"idle-turn": "Idle Turns",
		"empty-tool-result": "Empty Tool Results",
		"large-output-ignored": "Ignored Large Outputs",
	};
	return labels[type] ?? type;
}
