import { describe, it, expect } from "vitest";
import { generateMarkdownReport } from "../../src/report/markdown";

describe("generateMarkdownReport", () => {
	it("should generate markdown report with diagnostic data", () => {
		const diagnostic = {
			filePath: "CLAUDE.md",
			score: 85,
			issues: [
				{
					ruleId: "vague-rules",
					severity: "warning" as const,
					message: "Contains vague instructions",
					suggestion: "Be more specific",
				},
			],
			sections: [],
			missingSections: ["Commands"],
			lineCount: 50,
		};

		const md = generateMarkdownReport(null, diagnostic);
		expect(md).toContain("# AgentTuner Report");
		expect(md).toContain("**Score:** 85/100");
		expect(md).toContain("Contains vague instructions");
		expect(md).toContain("Commands");
		expect(md).toContain("Be more specific");
	});

	it("should generate markdown report with analysis data", () => {
		const analysis = {
			sessions: [],
			totalSessions: 5,
			totalTokensUsed: 10000,
			estimatedWastedTokens: 2000,
			estimatedWastedCost: 0.5,
			topWasteCategories: [
				{ type: "repeated-read", count: 3, tokens: 1500 },
				{ type: "exploration-loop", count: 2, tokens: 500 },
			],
		};

		const md = generateMarkdownReport(analysis, null);
		expect(md).toContain("## Session Analysis");
		expect(md).toContain("| Sessions | 5 |");
		expect(md).toContain("10.0K");
		expect(md).toContain("Repeated File Reads");
		expect(md).toContain("Exploration Loops");
	});

	it("should generate markdown report with both analysis and diagnostic", () => {
		const diagnostic = {
			filePath: "CLAUDE.md",
			score: 75,
			issues: [],
			sections: [],
			missingSections: [],
			lineCount: 30,
		};

		const analysis = {
			sessions: [],
			totalSessions: 0,
			totalTokensUsed: 0,
			estimatedWastedTokens: 0,
			estimatedWastedCost: 0,
			topWasteCategories: [],
		};

		const md = generateMarkdownReport(analysis, diagnostic);
		expect(md).toContain("## Config Diagnostic");
		expect(md).toContain("## Session Analysis");
		expect(md).toContain("75/100");
	});

	it("should handle null values", () => {
		const md = generateMarkdownReport(null, null);
		expect(md).toContain("# AgentTuner Report");
		expect(md).not.toContain("## Config Diagnostic");
		expect(md).not.toContain("## Session Analysis");
	});

	it("should include proper table formatting", () => {
		const analysis = {
			sessions: [],
			totalSessions: 10,
			totalTokensUsed: 5000,
			estimatedWastedTokens: 1000,
			estimatedWastedCost: 0.25,
			topWasteCategories: [],
		};

		const md = generateMarkdownReport(analysis, null);
		expect(md).toContain("| Metric | Value |");
		expect(md).toContain("|--------|-------|");
		expect(md).toContain("| Sessions | 10 |");
	});

	it("should format large numbers correctly", () => {
		const analysis = {
			sessions: [],
			totalSessions: 0,
			totalTokensUsed: 1500000,
			estimatedWastedTokens: 500000,
			estimatedWastedCost: 10.5,
			topWasteCategories: [],
		};

		const md = generateMarkdownReport(analysis, null);
		expect(md).toContain("1.5M");
		expect(md).toContain("500.0K");
	});

	it("should include issue severity icons", () => {
		const diagnostic = {
			filePath: "CLAUDE.md",
			score: 50,
			issues: [
				{
					ruleId: "test",
					severity: "error" as const,
					message: "Error message",
					suggestion: "Fix it",
				},
				{
					ruleId: "test2",
					severity: "warning" as const,
					message: "Warning message",
					suggestion: "Fix it",
				},
				{
					ruleId: "test3",
					severity: "info" as const,
					message: "Info message",
					suggestion: "Fix it",
				},
			],
			sections: [],
			missingSections: [],
			lineCount: 30,
		};

		const md = generateMarkdownReport(null, diagnostic);
		expect(md).toContain("🔴");
		expect(md).toContain("🟡");
		expect(md).toContain("🔵");
		expect(md).toContain("Error message");
		expect(md).toContain("Warning message");
		expect(md).toContain("Info message");
	});

	it("should include footer", () => {
		const md = generateMarkdownReport(null, null);
		expect(md).toContain("---");
		expect(md).toContain("Generated by [AgentTuner]");
	});

	it("should include missing sections", () => {
		const diagnostic = {
			filePath: "CLAUDE.md",
			score: 50,
			issues: [],
			sections: [],
			missingSections: ["Architecture", "Commands", "Constraints"],
			lineCount: 30,
		};

		const md = generateMarkdownReport(null, diagnostic);
		expect(md).toContain("### Missing Sections");
		expect(md).toContain("- Architecture");
		expect(md).toContain("- Commands");
		expect(md).toContain("- Constraints");
	});
});
